10回目のコミット
動きは完成したが、2週目に入るとバぐる。
MissingReferenceException: The object of type 'Card' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.MonoBehaviour.Invoke (System.String methodName, System.Single time) (at <3be1a7ff939c43f181c0a10b5a0189ac>:0)
Card.SetHide () (at Assets/_Scripts/Card.cs:127)
CardCreateManager.HideCardList (System.Collections.Generic.List`1[T] containCardIdList) (at Assets/_Scripts/CardCreateManager.cs:119)
GameSceneManager.Update () (at Assets/_Scripts/GameSceneManager.cs:87)